open($fh, '>', 'big.txt');
print $fh "5\n";
for(my $i=0; $i<5000; $i++) {
    $str = $str.'a';
    $str = $str.'b';
    $str = $str.'c';
    $str = $str.'d';
    $str = $str.'e';
    $str = $str.'f';
    $str = $str.'g';
    $str = $str.'h';
    $str = $str.'i';
    $str = $str.'j';
    $str = $str.'k';
    $str = $str.'l';
    $str = $str.'m';
    $str = $str.'n';
    $str = $str.'o';
    $str = $str.'p';
    $str = $str.'q';
    $str = $str.'s';
    $str = $str.'t';
    $str = $str.'r';
    $str = $str.'u';
    $str = $str.'v';
    $str = $str.'w';
    $str = $str.'x';
    $str = $str.'y';
    $str = $str.'z';
    $str = $str.'A';
    $str = $str.'B';
    $str = $str.'C';
    $str = $str.'D';
    $str = $str.'E';
    $str = $str.'F';
    $str = $str.'n';
    $str = $str.'o';
    $str = $str.'p';
    $str = $str.'q';
    $str = $str.'s';
    $str = $str.'t';
    $str = $str.'r';
    $str = $str.'u';
}
for(my $i=0; $i<5000; $i++) {
    $str2 = $str2.'F';
    $str2 = $str2.'E';
    $str2 = $str2.'f';
    $str2 = $str2.'h';
    $str2 = $str2.'u';
    $str2 = $str2.'a';
    $str2 = $str2.'j';
    $str2 = $str2.'v';
    $str2 = $str2.'a';
    $str2 = $str2.'n';
    $str2 = $str2.'t';
    $str2 = $str2.'q';
    $str2 = $str2.'p';
    $str2 = $str2.'l';
    $str2 = $str2.'k';
    $str2 = $str2.'m';
    $str2 = $str2.'z';
    $str2 = $str2.'A';
    $str2 = $str2.'a';
    $str2 = $str2.'u';
    $str2 = $str2.'a';
    $str2 = $str2.'v';
    $str2 = $str2.'c';
    $str2 = $str2.'j';
    $str2 = $str2.'n';
    $str2 = $str2.'w';
    $str2 = $str2.'B';
    $str2 = $str2.'r';
    $str2 = $str2.'i';
    $str2 = $str2.'t';
    $str2 = $str2.'a';
    $str2 = $str2.'j';
    $str2 = $str2.'v';
    $str2 = $str2.'a';
    $str2 = $str2.'C';
    $str2 = $str2.'t';
    $str2 = $str2.'F';
    $str2 = $str2.'E';
    $str2 = $str2.'l';
    $str2 = $str2.'k';
}
for (my $i=1;$i<=5;$i++) {
    print "test case 1\n";
    print $fh "200000 $str\n";
    printf $fh "200000 $str2\n";
}
